### PR TITLE
Setup

### LINKED ISSUE #1: Setup Astro project
We need to do the initial setup of the Astro project. We want to make sure to pick a premade theme as well. We're going with a premade theme because we're designers! We're just showing that we can set up a project and build off of it 👍

### LINKED ISSUE #2: Install and configure ESLint
Let's install and configure ESLint so we get some nice warnings and errors when we make syntax mistakes in our code. ESLint will also help us enforce coding conventions.

https://eslint.org

### LINKED ISSUE #3: Install and configure Prettier
Let's install Prettier to enable consistent code formatting throughout the codebase. I think Astro might give you the option to set this up when going through the Astro project setup.

 https://prettier.io

### LINKED ISSUE #4: Install Storybook
Let's install Storybook so we have a place to develop components in isolation. It's nice to develop components outside of the actual application so we know there aren't any hidden dependencies or coupling going on (we want to make sure components work _alone_, without needing other, arbitrary components).

https://storybook.js.org

### LINKED ISSUE #5: Add Astro+React integration
Let's use React as our framework integration for when we need interaction components. React is super popular and there are no shortage of jobs that desire experience with it.

https://docs.astro.build/en/guides/integrations-guide/react/

### PR DESCRIPTION
**Pull request by oacortez**
What (if any) features are you implementing?
- Set up Astro project 
- Installed ESlint 
- Installed Prettier
- Installed Storybook 
- Add React integration on astro project

What (if anything) did you refactor?
- Nothing at this time just added/installed packages and configurations

Were there any issues that arose?
- Not really an issue but I am concerned if I did my installations properly

Is there anything that you need from your teammate?
- I would like to get my files checked - package.json, .eslintrc.cjs, and any other configuration that I might need to update or might have missed

### CODE REVIEW

**Comment by kee-oth** [comment]
@oacortez 
I'm getting an error when running `npm run storybook`. Looks like there's a couple of ways to solve it:

**1) Upgrade to Storybook 7**

Unfortunately, Storybook 7 is not released yet so we can't do this yet but I'll make a ticket.



**2) Use a node v16 or earlier**

I don't know what version of node you're using because there's no way to tell in the project but I'm using node 18. We should add an `.nvmrc` file to track the node version so other developers can pull down the project and get everything going smoothly. I'll make a ticket for this as well.

I don't recommend this option though. I think we should stick with with the LTS (Long Term Support) version of node which is `v18.15.0` as it is the most up-to-date but stable version of node. That means we'd have to setup some way to switch node versions when running the Astro project (`v18.15.0`) vs when running the Storybook project (`v16.X.X`). I'm sure we could figure it out but one of the other options should work as well.



**3) Set `NODE_OPTIONS=--openssl-legacy-provider` when running Storybook.**  

This solution comes from this Storybook issue:
https://github.com/storybookjs/storybook/issues/19692#issuecomment-1444131263

I like this option. It's simple and I already tested it out and it works. This is technically a security vulnerability but we don't need to be concerned about that with this project at the moment.


The error (truncated):
```
this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports  {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Review by kee-oth — CHANGES_REQUESTED** [review]
@oacortez 
I'm getting an error when running `npm run storybook`. Looks like there's a couple of ways to solve it:

**1) Upgrade to Storybook 7**

Unfortunately, Storybook 7 is not released yet so we can't do this yet but I'll make a ticket. EDIT: [Here's the ticket](https://github.com/oacortez/portfolio/issues/8)



**2) Use a node v16 or earlier**

I don't know what version of node you're using because there's no way to tell in the project but I'm using node 18. We should add an `.nvmrc` file to track the node version so other developers can pull down the project and get everything going smoothly. I'll make a ticket for this as well. EDIT: [Here's the ticket](https://github.com/oacortez/portfolio/issues/7)

I don't recommend this option though. I think we should stick with with the LTS (Long Term Support) version of node which is `v18.15.0` as it is the most up-to-date but stable version of node. That means we'd have to setup some way to switch node versions when running the Astro project (`v18.15.0`) vs when running the Storybook project (`v16.X.X`). I'm sure we could figure it out but one of the other options should work as well.



**3) Set `NODE_OPTIONS=--openssl-legacy-provider` when running Storybook.**  

This solution comes from this Storybook issue:
https://github.com/storybookjs/storybook/issues/19692#issuecomment-1444131263

I like this option. It's simple and I already tested it out and it works. This is technically a security vulnerability but we don't need to be concerned about that with this project at the moment.


The error (truncated):
```
this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports  {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by oacortez** [comment]
@kee-oth 

- I just did the changes we discussed in issue #7 I added the .nvmrc and test it out using `nvm use`everything works great and hopefully there won't be any problems!

- on issue #8 I read the ticked and followed the comment solution you sent out to fix the `npm run storybook` error. As you mentioned how to fix the problem, using this command on the terminal `NODE_OPTIONS=--openssl-legacy-provider npm run storybook` I got it to fully run and start it up, but I wasn't able to set it up. I am not sure if I needed to do some configuration. I tried to put "NODE_OPTIONS=--openssl-legacy-provider npm run storybook" in my "start" script in package.json, but that did not work. Please let me know if I got anything mistaken!

**Comment by kee-oth** [comment]
@oacortez 

Regarding the Storybook issue, you just need to add `NODE_OPTIONS=--openssl-legacy-provider` to the Storybook script in the `package.json`

```json
"scripts": {
    "storybook": "NODE_OPTIONS=--openssl-legacy-provider start-storybook -p 6006",
```

It's not needed in the "start" script 👍

**Comment by oacortez** [comment]
@kee-oth 

I see! Thank you for pointing me on the right direction. I just fixed that error and adjust to what we talked about

**Review by kee-oth — APPROVED** [review]

**Pull request merged**
